[package]
name = "awaken-iam-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
awaken-iam-contract.workspace = true
thiserror.workspace = true

[lints]
workspace = true
